on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - name: Publish to GitHub Pages
      id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4      
      with:
        path: build
